# this is just a simple test device setup that's used to compile and test the examples

esphome:
  name: crow-runner-alarm
  friendly_name: Crow Runner Alarm

# esp32:
#   board: esp32dev
#   framework:
#     type: esp-idf
esp8266:
  early_pin_init: false
  board: d1

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  power_save_mode: HIGH
  output_power: 10db
  fast_connect: True
  manual_ip:
    static_ip: !secret home_manual_static_ip
    gateway: !secret home_manual_gateway
    subnet: 255.255.255.0

ota:
  - platform: esphome
    password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_encryption_key
