# this is just a simple test device setup that's used to compile and test the examples

esphome:
  name: crow-runner-alarm
  friendly_name: Crow Runner Alarm

# esp32:
#   board: esp32dev
#   framework:
#     type: esp-idf
esp8266:
  early_pin_init: false
  board: d1

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  manual_ip: !secret manual_wifi_ip
# web_server:
#   port: 80
#   version: 3

ota:
  - platform: esphome
    password: !secret ota_password
# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_encryption_key
